//
//  ListModels.swift
//  TodoListCleanSwift
//
//  Created by Denis Ivanov on 23.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum List {
	// MARK: Use cases
	
	enum Something {
		enum Request {
			case start
			case update(sections: [Section], id: UUID)
		}
		
		enum Response {
			case start(complitedTasks: [RegularTask], uncomplitedTasks: [RegularTask])
			case filtred(complitedTasks: [RegularTask], uncomplitedTasks: [RegularTask])
		}
		enum ViewModel {
			case initial([Section])
			case reload([Section])
		}
	}
}
