//
//  ListWorker.swift
//  TodoListCleanSwift
//
//  Created by Denis Ivanov on 23.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListWorker{
	
	private let sortedTaskManager: ITaskManager
	private let repo: IRepository
	
	init(taskManager: TaskManager = TaskManager()) {
		sortedTaskManager = SortedTaskManager(taskManager: taskManager)
	    repo = TasksRepository(taskManager: sortedTaskManager)
	}
	
	func setupTasks() {
		repo.setTasks()
	}
	
	func doSomeWork() -> ([RegularTask], [RegularTask]) {
		return (sortedTaskManager.getTasksCompleted(), sortedTaskManager.getTasksUnCompleted())
	}
}
