//
//  AuthRouter.swift
//  TodoListCleanSwift
//
//  Created by Denis Ivanov on 23.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AuthRoutingLogic {
  func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol AuthDataPassing {
  var dataStore: AuthDataStore? { get }
}

class AuthRouter: NSObject, AuthRoutingLogic, AuthDataPassing {
  weak var viewController: AuthViewController?
  var dataStore: AuthDataStore?
  
  // MARK: Routing
  
	func routeToSomewhere(segue: UIStoryboardSegue?) {
		if let segue = segue {
			let destinationVC = segue.destination as! ListViewController
			var sourseVC = segue.source as! AuthViewController
			navigateToSomewhere(source: sourseVC, destination: destinationVC)
		}
	}

  // MARK: Navigation
  
  func navigateToSomewhere(source: AuthViewController, destination: ListViewController) {
    source.show(destination, sender: nil)
  }
}
