//
//  AuthPresenter.swift
//  TodoListCleanSwift
//
//  Created by Denis Ivanov on 23.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthPresentationLogic {
	func presentSomething(response: Auth.Something.Response)
}

class AuthPresenter: AuthPresentationLogic {
	weak var viewController: AuthDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: Auth.Something.Response) {
		switch response {
		case .error(let descriptionError):
			viewController?.displaySomething(viewModel: .alert(title: "Ошибка", message: descriptionError))
		case .success:
			viewController?.displaySomething(viewModel: .transition)
		}
		
	}
}
