//
//  AuthWorker.swift
//  TodoListCleanSwift
//
//  Created by Denis Ivanov on 23.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class AuthWorker {
	
	enum State {
		case success
		case failure(description: String)
	}
	
	let authManager: IAuthManager
	
	init(authManager: IAuthManager) {
		self.authManager = authManager
	}
	
	func doSomeWork(login: String?, password: String?, completion: @escaping (State) -> Void) {
		guard let login = login, let password = password else {
			completion(.failure(description: "Поля незаполнены!"))
			return
		}

		guard !login.isEmpty else {
			completion(.failure(description: "Поле логин незаполнено"))
			return
		}
		guard !password.isEmpty else {
			completion(.failure(description: "Поле пароль незаполнено"))
			return
		}
		authManager.login(with: login, and: password) { authState in
			DispatchQueue.main.async {
				switch authState {
				case .successfully:
					completion(.success)
				case .invalidLogin:
					completion(.failure(description: "Неверный логин"))
				case .incorrectPassword:
					completion(.failure(description: "Неверный пароль"))
				}
			}
		}
	}
}
