//
//  AuthModels.swift
//  TodoListCleanSwift
//
//  Created by Denis Ivanov on 23.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Auth {
	// MARK: Use cases
	
	enum Something {
		enum Request {
			case auth(login: String?, password: String?)
		}
		
		enum Response {
			case error(String)
			case success
		}
		
		enum ViewModel {
			case alert(title: String, message: String)
			case transition
		}
	}
}
